#ifndef LIBNOISELUA_GLOBAL_H
#define LIBNOISELUA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNOISELUA_LIBRARY)
#  define LIBNOISELUASHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBNOISELUASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNOISELUA_GLOBAL_H
