#ifndef DIASPORAWIDGETS_GLOBAL_H
#define DIASPORAWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIASPORAWIDGETS_LIBRARY)
#  define DIASPORAWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIASPORAWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIASPORAWIDGETS_GLOBAL_H
