#ifndef LIBNOISEHELPERS_GLOBAL_H
#define LIBNOISEHELPERS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNOISEHELPERS_LIBRARY)
#  define LIBNOISEHELPERSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBNOISEHELPERSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNOISEHELPERS_GLOBAL_H
